app = 'r26'
primary_region = 'iad'

[build]

[env]
  PORT = '3026'

[http_service]
  internal_port = 3026
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = 'r26_data'
  destination = '/app/data'
