app = 'r26'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3026
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = 'r26_data'
  destination = '/app/data'
